# Generated by Django 2.2.1 on 2019-05-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sector name', max_length=50)),
                ('slug', models.CharField(help_text='Slug', max_length=50)),
                ('updated_at', models.DateTimeField(help_text='Updated time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sector name', max_length=50)),
                ('slug', models.CharField(help_text='Slug', max_length=50)),
                ('updated_at', models.DateTimeField(help_text='Updated time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.Sector')),
            ],
        ),
    ]
