# Generated by Django 2.2.1 on 2019-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated time')),
                ('name', models.CharField(help_text='Sector name', max_length=50)),
                ('slug', models.CharField(help_text='Slug', max_length=50)),
            ],
        ),
    ]
