# Generated by Django 2.2.1 on 2019-05-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20190525_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('name', 'slug', 'sector_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('name', 'slug')},
        ),
    ]
