# Generated by Django 2.2.1 on 2019-05-26 12:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20190526_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(help_text='Industry name', max_length=50),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=50)),
                ('symbol', models.CharField(help_text='Company symbol', max_length=50)),
                ('currency', models.CharField(help_text='Company currency', max_length=50, null=True)),
                ('xid', models.CharField(help_text='Company currency', max_length=50, null=True)),
                ('histories', django.contrib.postgres.fields.jsonb.JSONField(help_text='Company full history', null=True)),
                ('updated_at', models.DateTimeField(help_text='Updated time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
                ('industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='scrap.Sector')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'unique_together': {('name', 'symbol', 'industry_id')},
            },
        ),
    ]
