# Generated by Django 2.2.1 on 2019-05-26 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_auto_20190526_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='scrap.Industry'),
        ),
    ]
