# Generated by Django 2.2.1 on 2019-05-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_auto_20190526_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.CharField(help_text='Company url', max_length=50, null=True),
        ),
    ]
