# Generated by Django 2.2.1 on 2019-05-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_company_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.CharField(help_text='Company url', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='xid',
            field=models.CharField(help_text='Company currency', max_length=100, null=True),
        ),
    ]
