# Generated by Django 2.2.1 on 2019-05-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_auto_20190526_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company name', max_length=200),
        ),
    ]
