# Generated by Django 2.2.1 on 2019-05-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_auto_20190526_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='sector_id',
            new_name='sector',
        ),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('name', 'slug', 'sector')},
        ),
    ]
