# Generated by Django 2.2.1 on 2019-05-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_auto_20190529_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='industry_id',
            new_name='industry',
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'symbol', 'industry')},
        ),
    ]
