# Generated by Django 2.2.1 on 2019-06-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_auto_20190529_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='histories',
            new_name='history',
        ),
        migrations.AddField(
            model_name='company',
            name='history_updated_at',
            field=models.DateTimeField(help_text='Updated history time', null=True),
        ),
    ]
