# Generated by Django 2.2.1 on 2019-06-06 19:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0012_auto_20190606_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Company full history', null=True),
        ),
    ]
