# Generated by Django 2.2.1 on 2019-06-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0013_auto_20190606_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='history_updated_at',
            field=models.DateTimeField(blank=True, help_text='Updated history time', null=True),
        ),
    ]
