# Generated by Django 2.2.1 on 2019-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0014_auto_20190606_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, help_text='About the company', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.CharField(blank=True, help_text='Number of employees of the company', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='incorporated',
            field=models.CharField(blank=True, help_text='Incorporation year of the company', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, help_text='Headquarters address', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='net_income',
            field=models.CharField(blank=True, help_text='Web of the company', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='profile_updated_at',
            field=models.DateTimeField(blank=True, help_text='Updated profile time', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.CharField(blank=True, help_text='Revenue in the local currency', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, help_text='Web of the company', max_length=300, null=True),
        ),
    ]
