# Generated by Django 2.2.1 on 2019-06-10 19:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0015_auto_20190609_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Currency name', max_length=200)),
                ('symbol', models.CharField(help_text='Currency symbol', max_length=50)),
                ('link', models.CharField(help_text='Currency url', max_length=200, null=True)),
                ('xid_to_usd', models.CharField(help_text='Xid to USD conversion', max_length=100, null=True)),
                ('xid_from_usd', models.CharField(help_text='Xid to USD inverse conversion', max_length=100, null=True)),
                ('history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Company full history', null=True)),
                ('history_updated_at', models.DateTimeField(blank=True, help_text='Updated history time', null=True)),
                ('updated_at', models.DateTimeField(help_text='Updated time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'unique_together': {('name', 'symbol')},
            },
        ),
    ]
