# Generated by Django 2.2.1 on 2019-06-11 18:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0017_remove_currency_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='history',
        ),
        migrations.AddField(
            model_name='currency',
            name='history_from_usd',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Currency full history to USD inverse', null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='history_to_usd',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Currency full history to USD', null=True),
        ),
    ]
