# Generated by Django 2.2.1 on 2019-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0019_auto_20190616_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisys',
            name='number_of_days_sample',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisys',
            name='number_of_train_vectors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
