# Generated by Django 2.2.1 on 2019-06-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0020_auto_20190616_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisys',
            options={'verbose_name_plural': 'Analysis'},
        ),
        migrations.AlterUniqueTogether(
            name='analisys',
            unique_together={('company', 'kernel', 'svm', 'number_of_days_sample', 'number_of_train_vectors')},
        ),
    ]
