# Generated by Django 2.2.2 on 2019-06-18 05:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0021_auto_20190616_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisys',
            name='permutation_entropy',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
