# Generated by Django 2.2.2 on 2019-07-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0021_auto_20190616_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='svm_updated_at',
        ),
        migrations.AddField(
            model_name='analisys',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade of the kernel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='analysis_updated_at',
            field=models.DateTimeField(blank=True, help_text='Updated analysis time', null=True),
        ),
    ]
