# Generated by Django 2.2.2 on 2019-07-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0022_auto_20190715_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisys',
            old_name='grade',
            new_name='degree',
        ),
        migrations.AlterUniqueTogether(
            name='analisys',
            unique_together={('company', 'degree', 'svm', 'number_of_days_sample')},
        ),
        migrations.RemoveField(
            model_name='analisys',
            name='kernel',
        ),
        migrations.RemoveField(
            model_name='analisys',
            name='number_of_train_vectors',
        ),
    ]
