# Generated by Django 2.2.5 on 2019-11-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0024_auto_20191105_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisys',
            name='number_of_train_vectors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
