# Generated by Django 2.2.5 on 2019-11-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0025_analisys_number_of_train_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisys',
            name='fractal_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
